RET_OK = 0
RET_NOT_LOGIN = 1
RET_DBERROR = 2
RET_HTTP_PARAMETER_ERROR = 3
RET_STOCK_LACKING = 4
RET_NOT_START = 5
RET_IS_END = 5
RET_CART_NULL = 6
RET_NUM_OUT = 7
RET_SIZE_OCCUPIED = 8
RET_CART_OUT = 9
RET_ACTIVITY_NOT_START = 10
RET_ACTIVITY_HAS_END = 11
RET_OLD_BARCODE = 12

## register

RET_ACCOUNT_OCCUPATION = 12

###########
#
#wallet

RET_NOT_ENOUGH_BALANCE = 10010
RET_PAYMENT_VERIFY_FAILED = 10011
RET_VERIFY_MESSAGE_SENT_FAILED = 10012
RET_VERIFY_CODE_ERROR = 10013
RET_WITHDRAW_INSUFFICIENT_BALANCE = 10014


################
#
#coupons

RET_LIMITED_PRICE_NOT_SATISFY = 20001
RET_INVALID_GIFT_CODE  = 20002
RET_GIFT_CODE_ALREADY_USED = 20003

# orders
RET_NEED_PHONE_VERIFY = 3000
RET_HAVE_UNPAY_ORDER = 3001
